/**
 * Shared AI comparison response key lists.
 *
 * These keys are the names the Gemini AI uses when returning comparison
 * (supplier-vs-website) data.  Both ProductEntryForm and CompareDatasheets
 * need the same lists; keeping them here avoids drift.
 */

/** Keys that indicate a record has supplier/website comparison values */
export const COMPARISON_ROW_KEYS: readonly string[] = [
  "supplier",
  "supplier_data",
  "supplier_doc",
  "supplier_document",
  "supplier_extracted",
  "supplier_extraction",
  "supplier_sheet",
  "supplier_text",
  "supplier_raw",
  "supplier_value",
  "supplier_datasheet",
  "supplier_data_sheet",
  "supplier_data_value",
  "supplier_spec",
  "datasheet",
  "datasheet_a",
  "document_a",
  "doc_a",
  "source_a",
  "source_1",
  "a",
  "left",
  "ls",
  "ls_data",
  "ls_doc",
  "ls_document",
  "ls_extracted",
  "ls_extraction",
  "ls_sheet",
  "ls_text",
  "ls_raw",
  "ls_value",
  "ls_datasheet",
  "ls_data_sheet",
  "ls_data_value",
  "ls_spec",
  "website",
  "website_value",
  "website_text",
  "website_extracted",
  "lighting_style",
  "lighting_style_value",
  "datasheet_b",
  "document_b",
  "doc_b",
  "source_b",
  "source_a_value",
  "source_b_value",
  "source_2",
  "b",
  "right",
];

/** Candidate keys for the "supplier" inventory object in a nested response */
export const SUPPLIER_INVENTORY_KEYS: readonly string[] = [
  "supplier_inventory",
  "supplier_data",
  "supplier_values",
  "supplier_specs",
  "supplier_fields",
  "supplier_extracted_data",
  "supplier_extracted_fields",
  "supplier_extraction",
  "fields_a",
  "inventory_a",
  "datasheet_a_inventory",
  "document_a_inventory",
  "doc_a_inventory",
  "left_inventory",
  "source_a_inventory",
  "source_a_fields",
];

/** Candidate keys for the "LS / website" inventory object in a nested response */
export const LS_INVENTORY_KEYS: readonly string[] = [
  "ls_inventory",
  "website_inventory",
  "ls_data",
  "ls_values",
  "ls_specs",
  "ls_fields",
  "ls_extracted_data",
  "ls_extracted_fields",
  "ls_extraction",
  "website_fields",
  "fields_b",
  "inventory_b",
  "datasheet_b_inventory",
  "document_b_inventory",
  "doc_b_inventory",
  "right_inventory",
  "source_b_inventory",
  "source_b_fields",
];

/** Keys used to pick the "field" / row label from a comparison row */
export const FIELD_LABEL_KEYS: readonly string[] = [
  "field",
  "attribute",
  "property",
  "spec",
  "specification",
  "item",
  "key",
  "name",
  "label",
];

/** Keys used to pick the supplier value from a comparison row */
export const SUPPLIER_VALUE_KEYS: readonly string[] = [
  "supplier",
  "supplier_data",
  "supplier_doc",
  "supplier_document",
  "supplier_extracted",
  "supplier_extraction",
  "supplier_sheet",
  "supplier_text",
  "supplier_raw",
  "supplier_value",
  "supplier_datasheet",
  "supplier_data_sheet",
  "supplier_data_value",
  "supplier_spec",
  "datasheet",
  "datasheet_a",
  "document_a",
  "doc_a",
  "source_a",
  "source_a_value",
  "source_1",
  "a",
  "left",
];

/** Keys used to pick the LS / website value from a comparison row */
export const LS_VALUE_KEYS: readonly string[] = [
  "ls",
  "ls_data",
  "ls_doc",
  "ls_document",
  "ls_extracted",
  "ls_extraction",
  "ls_sheet",
  "ls_text",
  "ls_raw",
  "ls_value",
  "ls_datasheet",
  "ls_data_sheet",
  "ls_data_value",
  "ls_spec",
  "website",
  "website_value",
  "website_text",
  "website_extracted",
  "lighting_style",
  "lighting_style_value",
  "datasheet_b",
  "document_b",
  "doc_b",
  "source_b",
  "source_b_value",
  "source_2",
  "b",
  "right",
];
